spring:
  cloud:
    gateway:
      routes:
        - id: posts
          uri: ${BOARD_SERVICE_URL}
          predicates:
            - Path=/posts/**
          filters:
            - name: JwtAuthentication

        - id: auth
          uri: ${AUTH_SERVICE_URL}/auth
          predicates:
            - Path=/auth

        - id: member
          uri: ${AUTH_SERVICE_URL}/member
          predicates:
            - Path=/**
          filters:
            - name: JwtAuthentication