version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: school_reunion
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  board_app:
    container_name: board_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/school_reunion
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    restart: on-failure
    depends_on:
      - mysql

volumes:
  mysql: